import { GetStaticProps } from "next";
import Head from "next/head";
import { Book, getAllBooks } from "../data/book";

interface Props {
  books: Book[];
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const books = await getAllBooks();

  return {
    props: {
      books,
    },
  };
};

export default function Home({ books }: Props) {
  return (
    <div>
      <Head>
        <title>Logos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Logos</h1>

        {books.map((book) => {
          return (
            <div>
              <h2>{book.title}</h2>
              <h2>{book.description}</h2>
              <h2>{book.price}AZN</h2>
            </div>
          );
        })}
      </main>
    </div>
  );
}
